options:
    base_url:
        type: string
        description: Base URL of the service
    session_secret:
        type: string
        description: Secret key for signing session cookie IDs
    memcache_session_secret:
        type: string
        description: Secret key for encrypting session data stored in memcached
    sentry_dsn:
        type: string
        description: The Sentry DSN that will be used by Raven to send error reports to Sentry
    lp_api_username:
        type: string
        description: The username to use when communicating with Launchpad
    lp_api_consumer_key:
        type: string
        description: Launchpad OAuth consumer key
    lp_api_token:
        type: string
        description: Launchpad OAuth access token
    lp_api_token_secret:
        type: string
        description: Launchpad OAuth token secret
    github_auth_client_id:
        type: string
        description: GitHub client ID
    github_auth_client_secret:
        type: string
        description: GitHub client secret
    github_webhook_secret:
        type: string
        description: GitHub webhook secret
    poller_github_auth_token:
        type: string
        description: GitHub authorization token to be used exclusively by the poller
    poller_request_builds:
        type: string
        description: set to 'true' in order to allow poller to request builds
        default: "false"
    poller_build_threshold:
        type: string
        description: number of hours the poller should wait before requesting a build
        default: "24"
    http_proxy:
        type: string
        description: HTTP proxy URL
    db_name:
        default: "snap_build"
    db_roles:
        default: "snap_build"
