options:
    session_secret:
        type: string
        description: Secret key for signing session cookie IDs
    memcache_session_secret:
        type: string
        description: Secret key for encrypting session data stored in memcached
    sentry_dsn:
        type: string
        description: The Sentry DSN that will be used by Raven to send error reports to Sentry
    lp_api_username:
        type: string
        description: The username to use when communicating with Launchpad
    lp_api_consumer_key:
        type: string
        description: Launchpad OAuth consumer key
    lp_api_token:
        type: string
        description: Launchpad OAuth access token
    lp_api_token_secret:
        type: string
        description: Launchpad OAuth token secret
    github_auth_client_id:
        type: string
        description: GitHub client ID
    github_auth_client_secret:
        type: string
        description: GitHub client secret
    github_webhook_secret:
        type: string
        description: GitHub webhook secret
    http_proxy:
        type: string
        description: HTTP proxy URL
